
server:
  port: 8761

security:
  user:
    name: user
    password: password

eureka:
       
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 0 
    

        